### ALL ROLES
GET {{host}}//api/v1/roles
Accept: application/json

### ROLE BY NAME
@roleName = ROLE_MODERATOR
GET {{host}}//api/v1/roles/{{roleName}}

### CREATE ROLE
POST {{host}}//api/v1/roles
Content-Type: application/json

{
  "name": "ROLE_TEST"
}

### DELETE ROLE
@roleId = 4
DELETE {{host}}//api/v1/roles/{{roleId}}

### ASSIGN ROLE TO USER
@userId2 = f2018be9-7ba7-4a0f-84b6-5de1e5e28b6c
@roleId2 = 4
POST {{host}}//api/v1/users/assign-role-to-user?userId={{userId2}}&roleId={{roleId2}}
Content-Type: application/json

{
  "userId": "f2018be9-7ba7-4a0f-84b6-5de1e5e28b6c",
  "roleId": 4
}

### REMOVE ROLE FROM USER
@userId3 = f2018be9-7ba7-4a0f-84b6-5de1e5e28b6c
@roleId3 = 4
POST {{host}}//api/v1/users/remove-role-from-user?userId={{userId3}}&roleId={{roleId3}}

### REMOVE ALL USERS FROM ROLE
@roleId4 = 4
POST {{host}}//api/v1/users/remove-all-users-from-role?roleId={{roleId4}}